
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 317, in <module>
    eval(args.device,
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 140, in eval
    new_model.load_state_dict(t.load(saved_model_path))
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saved_models/profession-4-neuron-das masking_b16_e25.pth'
Traceback (most recent call last):
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 317, in <module>
    eval(args.device,
  File "/home/atticus/maheep/SAE_vs_DAS/main.py", line 140, in eval
    new_model.load_state_dict(t.load(saved_model_path))
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/atticus/.local/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'saved_models/profession-4-neuron-das masking_b16_e25.pth'