2024-05-22 11:13:30,927 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Configure stats pid to 1145
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/.config/wandb/settings
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Loading settings from /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/settings
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:_log_setup():520] Logging user logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_111330-d0h3srwp/logs/debug.log
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/maheepchaudhary/pytorch/Projects/concept_eraser_research/DAS_MAT/wandb/run-20240522_111330-d0h3srwp/logs/debug-internal.log
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x5d6287530>
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:init():560] calling init triggers
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-22 11:13:30,928 INFO    MainThread:1145 [wandb_init.py:init():585] re-initializing run, found existing run on stack: p7q6xua8
2024-05-22 11:13:30,929 INFO    MainThread:1145 [wandb_run.py:_finish():2103] finishing run counterfactuals/sae_concept_eraser/p7q6xua8
2024-05-22 11:13:30,929 INFO    MainThread:1145 [wandb_run.py:_atexit_cleanup():2343] got exitcode: 0
2024-05-22 11:13:30,930 INFO    MainThread:1145 [wandb_run.py:_restore():2326] restore
2024-05-22 11:13:30,930 INFO    MainThread:1145 [wandb_run.py:_restore():2332] restore done
2024-05-22 11:13:37,869 INFO    MainThread:1145 [wandb_init.py:init():610] starting backend
2024-05-22 11:13:37,869 INFO    MainThread:1145 [wandb_init.py:init():614] setting up manager
2024-05-22 11:13:37,870 INFO    MainThread:1145 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-22 11:13:37,870 INFO    MainThread:1145 [wandb_init.py:init():622] backend started and connected
2024-05-22 11:13:37,875 INFO    MainThread:1145 [wandb_run.py:_label_probe_notebook():1328] probe notebook
2024-05-22 11:13:37,875 INFO    MainThread:1145 [wandb_run.py:_label_probe_notebook():1338] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-05-22 11:13:37,875 INFO    MainThread:1145 [wandb_init.py:init():711] updated telemetry
2024-05-22 11:13:37,893 INFO    MainThread:1145 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
